import { test, expect } from "@playwright/test";
import * as fs from "fs";
import * as path from "path";

const MOCK_SCRIPT = `
  window.__t = {};
  Object.defineProperty(document, "modelContext", {
    value: { registerTool: (t) => { window.__t[t.name] = { _e: t.execute }; return Promise.resolve(); } },
    writable: false, configurable: true,
  });
`;

async function call(page: import("@playwright/test").Page, name: string, args: Record<string, unknown>) {
  return page.evaluate(async ({ n, a }) => {
    const t = (window as any).__t[n];
    if (!t) return { __error: n };
    return await t._e(a);
  }, { n: name, a: args });
}

test("Real Madrid → format_for_delivery → open in browser", async ({ page }) => {
  test.setTimeout(60000);
  await page.addInitScript(MOCK_SCRIPT);
  await page.goto("/");
  await page.waitForSelector("text=Edition No.", { timeout: 15000 });
  await page.waitForTimeout(1500);

  // Add Real Madrid stories
  const s1: any = await call(page, "openmemoz.add_story", {
    headline: "Kylian Mbappe Scores Hat-Trick in Champions League Opener",
    excerpt: "Kylian Mbappe marked his Champions League debut for Real Madrid with a stunning hat-trick, leading Los Blancos to a commanding 4-1 victory over RB Leipzig. The combination play with Vinicius Jr left defenders scrambling as the Santiago Bernabeu erupted.",
    section: "Sports",
    sourceName: "YouTube",
    sourceUrl: "https://www.youtube.com/watch?v=example1",
    youtubeVideoId: "dQw4w9WgXcQ",
    pinAsHero: true,
  });
  expect(s1.added).toBe(true);

  const s2: any = await call(page, "openmemoz.add_story", {
    headline: "Real Madrid Transfer Window Analysis: Building Around Mbappe",
    excerpt: "An in-depth look at how Carlo Ancelotti restructured the squad to maximize Mbappe's impact. The tactical shift to a fluid 4-2-3-1 allows Mbappe to drift centrally while Vinicius Jr holds the left flank. Midfield depth with Bellingham, Valverde, and Tchouameni means high pressing without sacrificing defensive stability.",
    section: "Sports",
    sourceName: "YouTube",
    sourceUrl: "https://www.youtube.com/watch?v=example2",
    youtubeVideoId: "9bZkp7q19f0",
  });
  expect(s2.added).toBe(true);

  // Format as newsletter
  const newsletter: any = await call(page, "openmemoz.format_for_delivery", {
    format: "newsletter",
    maxStories: 8,
  });
  expect(newsletter.format).toBe("newsletter");

  // Convert markdown to HTML
  let html = newsletter.content;
  html = html.replace(/^# (.+)$/gm, "<h1>$1</h1>");
  html = html.replace(/^\*([^*]+)\*$/gm, "<p class='meta'>$1</p>");
  html = html.replace(/^## (.+)$/gm, "<h2>$1</h2>");
  html = html.replace(/^### (.+)$/gm, "<h3>$1</h3>");
  html = html.replace(/^---$/gm, "<hr>");
  html = html.replace(/\*Source: \[([^\]]+)\]\(([^)]+)\)\*/g, '<p class="link">Source: <a href="$2">$1</a></p>');
  html = html.replace(/\*Watch: \[([^\]]+)\]\(([^)]+)\)\*/g, '<p class="link">Watch: <a href="$2">$1</a></p>');
  html = html.replace(/\*([^*]+)\*/g, "<em>$1</em>");
  html = html.replace(/^(?!<[hpe]|<hr|<a)(.{10,})$/gm, "<p>$1</p>");

  const fullHtml = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>OpenMemoz Newsletter</title>
<style>
body { font-family: Georgia, 'Times New Roman', serif; max-width: 720px; margin: 48px auto; padding: 0 28px; background: #0A0908; color: #EDEDF0; line-height: 1.8; }
h1 { font-size: 34px; border-bottom: 3px solid #D4A843; padding-bottom: 14px; margin-bottom: 4px; letter-spacing: -0.5px; }
h2 { font-size: 24px; color: #D4A843; margin-top: 40px; border-bottom: 1px solid rgba(212,168,67,0.25); padding-bottom: 6px; text-transform: uppercase; font-size: 16px; letter-spacing: 0.15em; }
h3 { font-size: 20px; margin-top: 20px; margin-bottom: 4px; }
p { margin: 6px 0; color: #c8c8d0; }
p.meta { color: #9C9CB0; font-style: italic; font-size: 14px; }
p.link { font-size: 13px; }
hr { border: none; border-top: 1px solid rgba(212,168,67,0.2); margin: 32px 0; }
em { color: #9C9CB0; font-size: 13px; }
a { color: #D4A843; text-decoration: none; }
a:hover { text-decoration: underline; }
.footer { text-align: center; font-size: 12px; color: #5C5C72; margin-top: 48px; padding: 20px 0; border-top: 1px solid rgba(212,168,67,0.2); }
.badge { display: inline-block; background: linear-gradient(135deg, #D4A843, #F59E0B); color: #0A0908; padding: 4px 14px; border-radius: 4px; font-size: 11px; font-family: system-ui, sans-serif; text-transform: uppercase; letter-spacing: 0.12em; font-weight: 700; margin-bottom: 16px; }
</style></head><body>
<div class="badge">WebMCP Delivery Test</div>
${html}
<div class="footer">
  Generated by <strong>openmemoz.format_for_delivery</strong> tool<br>
  OpenMemoz WebMCP &middot; Content from approved open sources only<br>
  Agent simulation &mdash; no ChatGPT subscription required
</div>
</body></html>`;

  const outputPath = path.join(__dirname, "..", "docs", "real-madrid-newsletter.html");
  fs.writeFileSync(outputPath, fullHtml);
});
